name: Run Python Script

on:
  schedule:
    - cron: '*/5 * * * *' # Runs at 00:00 UTC every Monday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
         
      - name: Run Python script
        env:
          JIRA_PASS: ${{ secrets.pass }}
        run: python Scripts/jira_issues.py
