name: Run Python Script

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      env:
        JIRA_PASS: ${{ secrets.pass }}
      run: python Scripts/jira_issues.py

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: extracted-issues
        path: C:/Users/k64152761/OneDrive - KONE Corporation/Documents/QADashboard/output/extracted_issues.csv
